doctrine:
    dbal:
        driver: 'sqlsrv'
        charset: UTF-8
        url: '%env(resolve:DATABASE_URL)%'
        types:
            geography:  App\Domain\DataTypes\Spatial\DBAL\Types\GeographyType
            linestring: App\Domain\DataTypes\Spatial\DBAL\Types\Geography\LineStringType
            point:      App\Domain\DataTypes\Spatial\DBAL\Types\Geography\PointType
            polygon:    App\Domain\DataTypes\Spatial\DBAL\Types\Geography\PolygonType
        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '5.7'
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Domain/Entity'
                prefix: 'App\Domain\Entity'
                alias: Domain
