twig:
    paths:
        '%kernel.project_dir%/src/Presentation/Web/Pub/Twig': Pub
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    exception_controller: null
    form_themes:
        - '@SemanticUi/form/semantic_2_layout.html.twig'
        - '@TetranzSelect2Entity/Form/fields.html.twig'